
services:
  web:
    image: proxy
    build:
      context: .
    # volumes:
    # - ./templates:/etc/nginx/templates
    ports:
    - "8080:80"
    environment:
    - NGINX_PORT=80
    - NGINX_PROXY_HOST=plweb-svc
    - NGINX_PROXY_PORT=9000