version: '3.8'

services:
  app:
    command: >
      sh -c "apk add --update npm
      && (cd /code/youtube && npm install)
      && (cd /code/youtube && npm run build)
      && python manage.py runserver 0.0.0.0:9000"
    volumes:
      - .:/code
    environment:
      - DEBUG=1
      - POSTGRES_HOST=db
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PORT=5432
      - DJANGO_SECRET_KEY='(^vaet+jq=h^q&(0v2kb#vity#526cxv6do(gd)hjuidz=d6'
    ports:
      - "9000:9000"
    networks:
      playlistener-network:    

networks:
  playlistener-network:
    external: true
    driver: bridge
    name: playlistener-network