version: '3.8'

services:
  app:
    restart: always
    volumes:
      - webassets:/var/www/html
    environment:
      - DEBUG=0
      - PRODUCTION=1
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    env_file:
      - .env
    networks:
      playlistener-network:

  proxy:
    image: nginx:alpine
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - webassets:/var/www/html:ro
    networks:
      playlistener-network:
        aliases:
          - playlistenerweb
    ports:
      - 9000:9000
    depends_on:
      - app

volumes:
  webassets: 

networks:
  playlistener-network:
    external: true
    driver: bridge
    name: playlistener-network
