version: '3.8'

services:
  webdb:
    image: postgres:alpine
    restart: always
    volumes:
      - dataweb:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      playlistener-network:   

  app:
    restart: always
    volumes:
      - dataweb:/data
      - webassets:/var/www/html
    environment:
      - DEBUG=0
      - PRODUCTION=1
    depends_on:
      - webdb
    env_file:
      - .env
    networks:
      playlistener-network:
        aliases:
          - playlistenerwebapp

  proxy:
    image: nginx:alpine
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - webassets:/var/www/html:ro
    networks:
      playlistener-network:
        aliases:
          - playlistenerweb
    ports:
      - 9000:9000
    depends_on:
      - app

volumes:
  dataweb:
    external: true
  webassets: 

networks:
  playlistener-network:
    external: true
    driver: bridge
    name: playlistener-network
