version: '3.8'

services:
  webdb:
    restart: always

  app:
    restart: always
    volumes:
      - dataweb:/code/data
      - webassets:/var/www/html
    environment:
      - DEBUG=0
      - PLAPI_PATH=http://playlistenerapiproxy:8000
    networks:
      playlistener-network:
        aliases:
          - playlistenerwebapp

  proxy:
    image: nginx:alpine
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - webassets:/var/www/html:ro
    networks:
      playlistener-network:
        aliases:
          - playlistenerweb
    ports:
      - 9000:9000
    depends_on:
      - app
