version: '3.8'

services:
  app:
    command: python manage.py runserver 0.0.0.0:9000
    volumes:
      - .:/code
    environment:
      - DEBUG=1
      - PRODUCTION=0
    ports:
      - "9000:9000"
    networks:
      playlistener-network:
