apiVersion: apps/v1
kind: Deployment
metadata:
  name: plweb
  namespace: plweb
spec:
  selector:
    matchLabels:
      app: plwebapp
  template:
    metadata:
      labels:
        app: plwebapp
    spec:
      containers:
        - name: plwebapp
          # image: registry.wieru.com/plweb
          image: nginx
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
          - containerPort: 80
            protocol: TCP
          envFrom:
          - configMapRef:
              name: plweb-config
          - secretRef:
              name: postgressecret
          - secretRef:
              name: app-secret

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: plwebdb
  namespace: plweb
spec:
  selector:
    matchLabels:
      app: plwebdb
  template:
    metadata:
      labels:
        app: plwebdb
    spec:
      containers:
        - name: plwebdb
          image: postgres:alpine
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
          - containerPort: 5432
            protocol: TCP
          envFrom:
          - configMapRef:
              name: plweb-config
          - secretRef:
              name: postgressecret
