apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-proxy
  namespace: plweb
spec:
  selector:
    matchLabels:
      app: app-proxy
  template:
    metadata:
      labels:
        app: app-proxy
    spec:
      volumes:
      - name: webassets
        persistentVolumeClaim:
          claimName: plwebassets
      containers:
        - name: app-proxy
          image: 192.168.1.100:32000/proxy:latest
          env:
          - name: NGINX_PORT
            value: "80"
          - name: NGINX_PROXY_HOST
            value: "app-svc"
          - name: NGINX_PROXY_PORT
            value: "80"
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
          volumeMounts:
          - mountPath: /var/www/html
            name: webassets