apiVersion: v1
kind: Service
metadata:
  name: plweb-proxy-svc
  namespace: plweb
spec:
  selector:
    app: plweb-proxy
  ports:
  - name: plweb-proxy
    protocol: TCP
    port: 80
    targetPort: 80
  type: NodePort

---

apiVersion: v1
kind: Service
metadata:
  name: plweb-svc
  namespace: plweb
spec:
  selector:
    app: plweb
  ports:
  - name: plweb
    protocol: TCP
    port: 80
    targetPort: 80
  type: NodePort
  
---

apiVersion: v1
kind: Service
metadata:
  name: plwebdb-svc
  namespace: plweb
spec:
  selector:
    app: plwebdb
  ports:
  - name: plwebdb
    protocol: TCP
    port: 5432
    targetPort: 5432