apiVersion: apps/v1
kind: Deployment
metadata:
  name: plweb
  namespace: plweb
spec:
  selector:
    matchLabels:
      app: plwebapp
  template:
    metadata:
      labels:
        app: plwebapp
    spec:
      containers:
        - name: plwebapp
          image: {{ .Values.image }}
          env:
            - name: ADMIN_USERNAME
              valueFrom:
                secretKeyRef:
                  name: adminsecret
                  key: ADMIN_USERNAME
                  optional: false
          envFrom:
          - configMapRef:
              name: plweb-configmap
          envFrom:
          - secretRef:
              name: postgressecret
          # envFrom:
          # - secretRef:
          #     name: adminsecret
          envFrom:
          - secretRef:
              name: djangosecret

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: plwebdb
  namespace: plweb
spec:
  selector:
    matchLabels:
      app: plwebdbapp
  template:
    metadata:
      labels:
        app: plwebdbapp
    spec:
      containers:
        - name: plwebdbapp
          image: postgres:alpine
          envFrom:
          - configMapRef:
              name: plweb-configmap
          envFrom:
          - secretRef:
              name: postgressecret