apiVersion: apps/v1
kind: Deployment
metadata:
  name: plweb
  namespace: plweb
spec:
  selector:
    matchLabels:
      app: plwebapp
  template:
    metadata:
      labels:
        app: plwebapp
    spec:
      containers:
        - name: plwebapp
          image: {{ .Values.image }}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: plwebdb
  namespace: plweb
spec:
  selector:
    matchLabels:
      app: plwebdbapp
  template:
    metadata:
      labels:
        app: plwebdbapp
    spec:
      containers:
        - name: plwebdbapp
          image: postgres:alpine
          envFrom:
          - configMapRef:
              name: plweb-configmap
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgressecret
                  key: username
                  optional: false
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgressecret
                  key: password
                  optional: false
            # - name: POSTGRES_HOST
            #   valueFrom:
            #     configMapKeyRef:
            #       name: plweb-configmap
            #       key: POSTGRES_HOST
            # - name: POSTGRES_DB
            #   valueFrom:
            #     configMapKeyRef:
            #       name: plweb-configmap
            #       key: POSTGRES_DB
            # - name: ADMIN_USERNAME
            #   valueFrom:
            #     secretKeyRef:
            #       name: adminsecret
            #       key: username
            #       optional: false
            # - name: ADMIN_PASSWORD
            #   valueFrom:
            #     secretKeyRef:
            #       name: adminsecret
            #       key: password
            #       optional: false
            # - name: DJANGO_SECRET_KEY
            #   valueFrom:
            #     secretKeyRef:
            #       name: djangosecret
            #       key: secret
            #       optional: false           
            # - name: GO_PIPELINE_LABEL
            #   valueFrom:
            #     configMapKeyRef:
            #       name: plweb-configmap
            #       key: GO_PIPELINE_LABEL
            # - name: PLAPI_PATH
            #   valueFrom:
            #     configMapKeyRef:
            #       name: plweb-configmap
            #       key: PLAPI_PATH