apiVersion: apps/v1
kind: Deployment
metadata:
  name: plweb
  namespace: plweb
spec:
  selector:
    matchLabels:
      app: plwebapp
  template:
    metadata:
      labels:
        app: plwebapp
    spec:
      containers:
        - name: plwebapp
          image: {{ .Values.image }}
          envFrom:
          - configMapRef:
              name: plweb-configmap
          - secretRef:
              name: postgressecret
          - secretRef:
              name: adminsecret
          - secretRef:
              name: djangosecret

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: plwebdb
  namespace: plweb
spec:
  selector:
    matchLabels:
      app: plwebdbapp
  template:
    metadata:
      labels:
        app: plwebdbapp
    spec:
      containers:
        - name: plwebdbapp
          image: postgres:alpine
          envFrom:
          - configMapRef:
              name: plweb-configmap
          envFrom:
          - secretRef:
              name: postgressecret